import { title } from "process";

// lib/projects-data.ts
export const projects = [
  {
    id: "Heroes",
    title: "Heroes",
    category: "Game Development",
    duration: "2 Weeks",
    description:
      "Game RPG Medival dengan Third Person View, fitur crafting, dan sistem quest yang mendalam.",
    fullDescription:
      "Game RPG dengan setting medieval yang menawarkan pengalaman bermain yang imersif. Fitur utama termasuk mekanik crafting yang kompleks, sistem quest yang mendalam, dan dunia terbuka yang luas untuk dijelajahi.",
    background:
      "Heroes adalah proyek game RPG yang dikembangkan untuk memberikan pengalaman bermain yang mendalam dan imersif. Game ini dirancang dengan fokus pada mekanik crafting yang kompleks, sistem quest yang kaya, dan dunia terbuka yang luas untuk dijelajahi oleh para pemain.",
    objectives: [
      "Menyediakan pengalaman RPG yang imersif dengan mekanik crafting yang kompleks",
      "Membangun sistem quest yang mendalam untuk meningkatkan engagement pemain",
    ],
    images: ["/project/Heroes.webp"],
    image: "/project/Heroes.webp",
    technologies: [
      "Unity",
      "C#",
      "Blender",
      "Adobe Illustrator",
      "Adobe After Effects",
      "Adobe Premiere",
    ],
    liveLink: "",
    githubLink: undefined,
    featured: true,
    stats: {
      users: "10+",
      completionDate: "April 2026",
      rating: 4.7,
    },
    status: "Live",
  },
  {
    id: "pingx",
    title: "PingX",
    category: "Node Package Manager",
    duration: "1 Weeks",
    description:
      "Node.js package untuk monitoring latency server dan koneksi jaringan dengan tampilan yang sudah dioptimalkan.",
    fullDescription:
      "Node.js package untuk monitoring latency server dan koneksi jaringan dengan tampilan yang sudah dioptimalkan.",
    background:
      "PingX adalah paket Node.js open source yang dirancang untuk memantau latency server dan koneksi jaringan secara real-time. Paket ini menyediakan antarmuka yang mudah digunakan dan visualisasi data yang informatif untuk membantu pengembang mengidentifikasi dan mengatasi masalah jaringan dengan cepat.",
    objectives: [
      "Menyediakan alat monitoring latency yang mudah digunakan",
      "Memberikan visualisasi data yang informatif",
    ],
    images: ["/project/PingX.webp"],
    image: "/project/PingX.webp",
    technologies: ["Node.js", "Javascript"],
    liveLink: "https://www.npmjs.com/package/@xavorus/pingx",
    githubLink: "https://github.com/KwikAndreas/pingx",
    featured: false,
    stats: {
      users: "415+",
      completionDate: "November 2025",
      rating: 4.9,
    },
    status: "Live",
  },
  {
    id: "kelasbios",
    title: "Kelas BIOS",
    category: "Web Development",
    client: "Organization Project",
    duration: "2 days",
    description:
      "Platform pendaftaran online untuk anggota dan sesi kelas Himpunan Mahasiswa Informatika (HIMA BIOS).",
    fullDescription:
      "Platform pendaftaran online yang memudahkan calon anggota HIMA BIOS untuk mendaftar sebagai anggota serta mengikuti sesi kelas dan workshop yang diselenggarakan oleh organisasi.",
    background:
      "HIMA BIOS membutuhkan sistem pendaftaran digital untuk mengelola anggota dan peserta kelas secara efisien. Sistem manual sebelumnya menyebabkan kesulitan dalam tracking pendaftaran dan komunikasi dengan calon anggota.",
    objectives: [
      "Meningkatkan efisiensi proses pendaftaran anggota",
      "Mempermudah calon anggota dalam mengakses informasi kelas",
      "Implementasi sistem notifikasi otomatis untuk pendaftaran",
    ],
    images: [
      "/project/kelasbios_home.webp",
      "/project/kelasbios_dashboard.webp",
      "/project/kelasbios_admin.webp",
    ],
    image: "/project/kelasbios_home.webp",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
    liveLink: "https://kelasbios.vercel.app",
    githubLink: "https://github.com/KwikAndreas/kelasbios",
    featured: false,
    stats: {
      users: "40+",
      rating: 4.8,
      completionDate: "Maret 2026",
    },
    status: "Live",
  },
  {
    id: "biosfest",
    title: "BIOS Festival",
    category: "Web Development",
    client: "Organization Project",
    duration: "2 Weeks",
    description:
      "Website Resmi Seminar dan Lomba Nasional BIOS Festival dengan fitur pendaftaran online dan informasi acara.",
    fullDescription:
      "Website institusional untuk acara tahunan BIOS Festival yang menampilkan informasi lengkap tentang seminar, lomba, pembicara, jadwal acara, dan formulir pendaftaran online.",
    background:
      "BIOS Festival adalah acara tahunan yang diselenggarakan oleh Himpunan Mahasiswa Bioinformatika (HIMA BIOS). Acara ini bertujuan untuk meningkatkan pengetahuan dan keterampilan mahasiswa di bidang bioinformatika melalui seminar dan kompetisi. Sebelumnya, pendaftaran dilakukan secara manual yang menyulitkan peserta dan panitia.",
    objectives: [
      "Meningkatkan brand awareness acara BIOS Festival",
      "Menyediakan platform pendaftaran online yang efisien",
      "Menyajikan informasi acara secara terstruktur dan menarik",
      "Mempermudah komunikasi antara panitia dan peserta",
    ],
    images: [
      "/project/biosfest/biosfest.vercel.app_landing_page.webp",
      "/project/biosfest/biosfest.vercel.app_3card.webp",
      "/project/biosfest/biosfest.vercel.app_kategori_lomba_uiux.webp",
      "/project/biosfest/biosfest.vercel.app_kategori_lomba_web.webp",
      "/project/biosfest/biosfest.vercel.app_kategori_lomba_game.webp",
      "/project/biosfest/biosfest.vercel.app_timeline1.webp",
      "/project/biosfest/biosfest.vercel.app_timeline2.webp",
      "/project/biosfest/biosfest.vercel.app_partisipasi.webp",
      "/project/biosfest/biosfest.vercel.app_footer.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_sma_landingpage.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_sma_ketentuan_lomba.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_sma_kriteria_penilaian.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_sma_timeline.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_sma_footer.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_webdev_landingpage.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_webdev_ketentuan_lomba.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_webdev_kriteria_penilaian.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_webdev_timeline.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_game_landingpage.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_game_ketentuan_lomba.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_game_kriteria_penilaian.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_game_timeline.webp",
      "/project/biosfest/biosfest.vercel.app_lomba_mahasiswa_game_footer.webp",
    ],
    image: "/project/biosfest/biosfest.vercel.app_landing_page.webp",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Supabase",
      "Vercel",
    ],
    liveLink: "https://biosfest.vercel.app",
    githubLink: "https://github.com/KwikAndreas/biosfest",
    featured: false,
    stats: {
      users: "300+",
      completionDate: "Januari 2025",
      rating: 4.8,
    },
    status: "Abandoned",
  },

  {
    id: "biosmerch",
    title: "BIOS Merchandise",
    category: "Web Development",
    client: "Organization Project",
    duration: "5 days",
    description:
      "E-commerce platform untuk penjualan merchandise organisasi BIOS dengan sistem katalog produk.",
    fullDescription:
      "Platform e-commerce komprehensif yang dikembangkan khusus untuk organisasi BIOS (Bioinformatics Student Organization). Fitur mencakup katalog produk interaktif, sistem keranjang belanja, integrasi payment gateway Stripe, order tracking, dan dashboard admin untuk manajemen produk dan pesanan.",
    background:
      "Organisasi BIOS membutuhkan platform digital untuk menjual merchandise resmi seperti kaos, tote bag, dan aksesoris lainnya kepada mahasiswa dan alumni. Sebelumnya penjualan dilakukan secara manual yang tidak efisien dan sulit untuk tracking.",
    objectives: [
      "Digitalisasi sistem penjualan merchandise organisasi",
      "Menyediakan platform yang user-friendly untuk mahasiswa berbelanja",
      "Implementasi sistem payment yang aman dan terpercaya",
      "Memberikan dashboard admin untuk manajemen inventory dan orders",
    ],
    images: ["/project/merchbios.webp"],
    image: "/project/merchbios.webp",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
    liveLink: "https://merchbios.vercel.app",
    githubLink: "https://github.com/KwikAndreas/merchbios",
    featured: false,
    stats: {
      users: "120+",
      completionDate: "September 2025",
      rating: 4.3,
    },
    status: "Abandoned",
  },
  {
    id: "himabios",
    title: "Hima BIOS",
    category: "Web Development",
    client: "Organization Project",
    duration: "2 weeks",
    description:
      "Website resmi Himpunan Mahasiswa BIOS dengan fitur informasi organisasi.",
    fullDescription:
      "Website institusional untuk Himpunan Mahasiswa Bioinformatika (HIMA BIOS) yang berfungsi sebagai hub informasi dan komunikasi. Platform ini menampilkan profil organisasi, struktur kepengurusan, agenda kegiatan, blog artikel bioinformatika.",
    background:
      "HIMA BIOS membutuhkan presence digital yang profesional untuk meningkatkan visibilitas organisasi, mempermudah komunikasi dengan mahasiswa, dan sebagai platform informasi terpusat. Website lama tidak responsive dan sulit diupdate oleh pengurus.",
    objectives: [
      "Meningkatkan brand awareness dan profesionalisme organisasi",
      "Menyediakan platform informasi terpusat untuk mahasiswa",
      "Memfasilitasi registrasi dan komunikasi event secara digital",
      "Memberikan portal anggota untuk akses konten eksklusif",
    ],
    images: [
      "/project/himabios.webp",
      "/project/himabios_learn.webp",
      "/project/himabios_about.webp",
      "/project/himabios_announcement.webp",
    ],
    image: "/project/himabios.webp",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React Hook Form"],
    liveLink: "https://himabios.vercel.app",
    githubLink: "https://github.com/KwikAndreas/himabios",
    featured: false,
    stats: {
      users: "120+",
      rating: 5.0,
      completionDate: "September 2025",
    },
    status: "Live",
  },
  {
    id: "gki-cipinang-indah",
    title: "GKI Cipinang Indah",
    category: "Web Development",
    client: "GKI Cipinang Indah Church",
    duration: "3 months",
    description:
      "Website gereja modern dengan sistem manajemen jemaat, jadwal ibadah, dan platform donasi online. Dibangun dengan Next.js dan PostgreSQL.",
    fullDescription:
      "Platform digital komprehensif untuk gereja yang mencakup sistem registrasi jemaat, manajemen acara, streaming ibadah online, dan integrasi pembayaran untuk donasi.",
    background:
      "Gereja membutuhkan platform digital untuk mengelola jemaat dan mempermudah akses informasi ibadah, terutama setelah pandemi COVID-19 yang mengharuskan adaptasi teknologi.",
    objectives: [
      "Menyediakan platform digital untuk manajemen jemaat",
      "Memfasilitasi streaming ibadah online",
      "Mengintegrasikan sistem donasi digital",
      "Meningkatkan engagement komunitas gereja",
    ],
    images: [
      "/project/gkicinda_home.webp",
      "/project/gkicinda_youtube.webp",
      "/project/gkicinda_jadwal.webp",
      "/project/gkicinda_renungan.webp",
      "/project/gkicinda_profile.webp",
      "/project/gkicinda_artikel.webp",
      "/project/gkicinda_info.webp",
      "/project/gkicinda_kalender.webp",
      "/project/gkicinda_download.webp",
    ],
    image: "/project/gkicinda.webp",
    technologies: [
      "Next.js",
      "Vite",
      "TypeScript",
      "PostgreSQL",
      "Supabase",
      "Tailwind CSS",
    ],
    liveLink: "https://gkicinda.id",
    githubLink: "https://github.com/KwikAndreas/GKI-CINDA",
    featured: true,
    stats: {
      users: "900+",
      rating: 5.0,
      completionDate: "August 2025",
    },
    status: "Live",
  },

  {
    id: "waste-sorter",
    title: "Waste Sorter",
    category: "Game Development",
    client: "Educational Initiative",
    duration: "1.5 months",
    description:
      "Game edukasi untuk memilah sampah dengan mekanik drag-and-drop, leaderboard, dan sistem reward.",
    fullDescription:
      "Game interaktif yang mengajarkan pemain tentang pentingnya daur ulang dan pengelolaan sampah. Fitur termasuk berbagai level, tantangan waktu, dan integrasi media sosial.",
    background:
      "Inisiatif edukasi lingkungan untuk meningkatkan kesadaran masyarakat tentang pentingnya pengelolaan sampah dan daur ulang melalui gamifikasi.",
    objectives: [
      "Edukasi pengelolaan sampah yang benar",
      "Meningkatkan kesadaran lingkungan",
      "Gamifikasi pembelajaran sustainability",
      "Engagement melalui kompetisi dan leaderboard",
    ],
    images: ["/project/waste_sorter.webp"],
    image: "/project/waste_sorter.webp",
    technologies: [
      "Unity",
      "C#",
      "Python",
      "TensorFlow",
      "CNN",
      "Blender",
      "Adobe Illustrator",
    ],
    liveLink: "https://bit-grow.itch.io/waste-sorter",
    githubLink: undefined,
    featured: false,
    stats: {
      users: "40+",
      rating: 5.0,
      completionDate: "Nov 2024",
    },
    status: "Live",
  },
  {
    id: "car-rush",
    title: "Car Rush",
    category: "Game Development",
    client: "Personal Project",
    duration: "2 months",
    description:
      "Game mobile endless runner dengan Unity 3D. Fitur multiplayer real-time, sistem upgrade kendaraan, dan leaderboard global.",
    fullDescription:
      "Game racing mobile dengan mekanik endless runner, sistem monetisasi in-app purchase, analytics terintegrasi, dan cloud save functionality.",
    background:
      "Proyek personal untuk mengeksplorasi game development dengan Unity dan mempelajari implementasi sistem multiplayer real-time dalam mobile gaming.",
    objectives: [
      "Mengembangkan game mobile yang engaging",
      "Implementasi sistem multiplayer real-time",
      "Integrasi monetisasi in-app purchase",
      "Optimasi performa untuk berbagai device mobile",
    ],
    images: ["/project/carrush.webp"],
    image: "/project/carrush.webp",
    technologies: ["Unity", "C#", "Blender", "Adobe Illustrator"],
    liveLink: "https://bit-grow.itch.io/carrush",
    githubLink: undefined,
    featured: false,
    stats: {
      users: undefined,
      rating: undefined,
      completionDate: "June 2023",
    },
    status: "Abandoned",
  },
] as const;
